### ISSUE TITLE
example config.php

### ISSUE THREAD

**Issue by nealrs** [jshawl/unqueue#6]
@jshawl this looks pretty neat. can you please upload an example `config.php` file -- so I know which vars I have to config? I want to use this to create a similar project (auto-add every link from Nextdraft to my pocket list)

or actually, is the config.php the same as from `pocket-oauth-php`?

**Comment by jshawl** [comment]
@nealrs yep you only need the first two variables - https://github.com/jshawl/pocket-oauth-php/blob/288cd2cb8fb2196e820cf9d36844c3511fb7b2c0/config.php#L2-L5

**Comment by nealrs** [comment]
Awesome, thanks!
